verbose        = "yes"

[cosmos]
prefix         = "migaloo"
denomination   = "uwhale"

[testnets]
    [testnets.theta]
    node_url = "http://65.21.232.185:2001/"
    chain_id = "narwhal-1"
    faucet_address = "migaloo10cmarhna5d2cjh5ugfmv4a50pf3dufdte2lt2y"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "500"


[discord]
bot_token = ""
# comma separated list of channels
channels_to_listen = "general"
# how often user can request tokens from faucet (seconds)
# 10800 = 3  hours
# 86400 = 24 hours
request_timeout    = "86400"
